### ISSUE TITLE
what is your performance?

### ISSUE THREAD

**Issue by Jasperty** [vanangamudi/dcn_squad#1]

**Comment by vanangamudi** [comment]
around 90 percent at the time. haven't been working on this. kindly let me know in case you're run this.

**Comment by Jasperty** [comment]
> around 90 percent at the time. haven't been working on this. kindly let me know in case you're run this.

hi, on the paper, dcn+ get f1 of 83.1 and em of  74.5 on squad1.1, are you reach this? i want to run dcn+ to get the original score to do some research, and your code is the best readable.

**Comment by vanangamudi** [comment]
This is not DCN+. I think DCN+ uses some form of reinforcement to account for misalignment. This implementation is just DCN with the answer selection layer as a FC layer, that projects onto the answer vocabulary. The dataset was filtered such a way that the samples are only single word answers. This model got around 92 percent overall accuracy for similar subset of bAbI.
